#include "vallex.h"

// const auto mapKeys =[
//         'ar_text_embedding.word_embeddings.weight',
//         'nar_text_embedding.word_embeddings.weight',
//         'ar_audio_embedding.word_embeddings.weight',
//         'ar_text_position.alpha',
//         'ar_audio_position.alpha',
//         'ar_decoder.layers.0.self_attn.in_proj_weight',
//         'ar_decoder.layers.0.self_attn.in_proj_bias',
//         'ar_decoder.layers.0.self_attn.out_proj.weight',
//         'ar_decoder.layers.0.self_attn.out_proj.bias',
//         'ar_decoder.layers.0.linear1.weight',
//         'ar_decoder.layers.0.linear1.bias',
//         'ar_decoder.layers.0.linear2.weight',
//         'ar_decoder.layers.0.linear2.bias',
//         'ar_decoder.layers.0.norm1.weight',
//         'ar_decoder.layers.0.norm1.bias',
//         'ar_decoder.layers.0.norm2.weight',
//         'ar_decoder.layers.0.norm2.bias',
//         'ar_decoder.layers.1.self_attn.in_proj_weight',
//         'ar_decoder.layers.1.self_attn.in_proj_bias',
//         'ar_decoder.layers.1.self_attn.out_proj.weight',
//         'ar_decoder.layers.1.self_attn.out_proj.bias',
//         'ar_decoder.layers.1.linear1.weight',
//         'ar_decoder.layers.1.linear1.bias',
//         'ar_decoder.layers.1.linear2.weight',
//         'ar_decoder.layers.1.linear2.bias',
//         'ar_decoder.layers.1.norm1.weight',
//         'ar_decoder.layers.1.norm1.bias',
//         'ar_decoder.layers.1.norm2.weight',
//         'ar_decoder.layers.1.norm2.bias',
//         'ar_decoder.layers.2.self_attn.in_proj_weight',
//         'ar_decoder.layers.2.self_attn.in_proj_bias',
//         'ar_decoder.layers.2.self_attn.out_proj.weight',
//         'ar_decoder.layers.2.self_attn.out_proj.bias',
//         'ar_decoder.layers.2.linear1.weight',
//         'ar_decoder.layers.2.linear1.bias',
//         'ar_decoder.layers.2.linear2.weight',
//         'ar_decoder.layers.2.linear2.bias',
//         'ar_decoder.layers.2.norm1.weight',
//         'ar_decoder.layers.2.norm1.bias',
//         'ar_decoder.layers.2.norm2.weight',
//         'ar_decoder.layers.2.norm2.bias',
//         'ar_decoder.layers.3.self_attn.in_proj_weight',
//         'ar_decoder.layers.3.self_attn.in_proj_bias',
//         'ar_decoder.layers.3.self_attn.out_proj.weight',
//         'ar_decoder.layers.3.self_attn.out_proj.bias',
//         'ar_decoder.layers.3.linear1.weight',
//         'ar_decoder.layers.3.linear1.bias',
//         'ar_decoder.layers.3.linear2.weight',
//         'ar_decoder.layers.3.linear2.bias',
//         'ar_decoder.layers.3.norm1.weight',
//         'ar_decoder.layers.3.norm1.bias',
//         'ar_decoder.layers.3.norm2.weight',
//         'ar_decoder.layers.3.norm2.bias',
//         'ar_decoder.layers.4.self_attn.in_proj_weight',
//         'ar_decoder.layers.4.self_attn.in_proj_bias',
//         'ar_decoder.layers.4.self_attn.out_proj.weight',
//         'ar_decoder.layers.4.self_attn.out_proj.bias',
//         'ar_decoder.layers.4.linear1.weight',
//         'ar_decoder.layers.4.linear1.bias',
//         'ar_decoder.layers.4.linear2.weight',
//         'ar_decoder.layers.4.linear2.bias',
//         'ar_decoder.layers.4.norm1.weight',
//         'ar_decoder.layers.4.norm1.bias',
//         'ar_decoder.layers.4.norm2.weight',
//         'ar_decoder.layers.4.norm2.bias',
//         'ar_decoder.layers.5.self_attn.in_proj_weight',
//         'ar_decoder.layers.5.self_attn.in_proj_bias',
//         'ar_decoder.layers.5.self_attn.out_proj.weight',
//         'ar_decoder.layers.5.self_attn.out_proj.bias',
//         'ar_decoder.layers.5.linear1.weight',
//         'ar_decoder.layers.5.linear1.bias',
//         'ar_decoder.layers.5.linear2.weight',
//         'ar_decoder.layers.5.linear2.bias',
//         'ar_decoder.layers.5.norm1.weight',
//         'ar_decoder.layers.5.norm1.bias',
//         'ar_decoder.layers.5.norm2.weight',
//         'ar_decoder.layers.5.norm2.bias',
//         'ar_decoder.layers.6.self_attn.in_proj_weight',
//         'ar_decoder.layers.6.self_attn.in_proj_bias',
//         'ar_decoder.layers.6.self_attn.out_proj.weight',
//         'ar_decoder.layers.6.self_attn.out_proj.bias',
//         'ar_decoder.layers.6.linear1.weight',
//         'ar_decoder.layers.6.linear1.bias',
//         'ar_decoder.layers.6.linear2.weight',
//         'ar_decoder.layers.6.linear2.bias',
//         'ar_decoder.layers.6.norm1.weight',
//         'ar_decoder.layers.6.norm1.bias',
//         'ar_decoder.layers.6.norm2.weight',
//         'ar_decoder.layers.6.norm2.bias',
//         'ar_decoder.layers.7.self_attn.in_proj_weight',
//         'ar_decoder.layers.7.self_attn.in_proj_bias',
//         'ar_decoder.layers.7.self_attn.out_proj.weight',
//         'ar_decoder.layers.7.self_attn.out_proj.bias',
//         'ar_decoder.layers.7.linear1.weight',
//         'ar_decoder.layers.7.linear1.bias',
//         'ar_decoder.layers.7.linear2.weight',
//         'ar_decoder.layers.7.linear2.bias',
//         'ar_decoder.layers.7.norm1.weight',
//         'ar_decoder.layers.7.norm1.bias',
//         'ar_decoder.layers.7.norm2.weight',
//         'ar_decoder.layers.7.norm2.bias',
//         'ar_decoder.layers.8.self_attn.in_proj_weight',
//         'ar_decoder.layers.8.self_attn.in_proj_bias',
//         'ar_decoder.layers.8.self_attn.out_proj.weight',
//         'ar_decoder.layers.8.self_attn.out_proj.bias',
//         'ar_decoder.layers.8.linear1.weight',
//         'ar_decoder.layers.8.linear1.bias',
//         'ar_decoder.layers.8.linear2.weight',
//         'ar_decoder.layers.8.linear2.bias',
//         'ar_decoder.layers.8.norm1.weight',
//         'ar_decoder.layers.8.norm1.bias',
//         'ar_decoder.layers.8.norm2.weight',
//         'ar_decoder.layers.8.norm2.bias',
//         'ar_decoder.layers.9.self_attn.in_proj_weight',
//         'ar_decoder.layers.9.self_attn.in_proj_bias',
//         'ar_decoder.layers.9.self_attn.out_proj.weight',
//         'ar_decoder.layers.9.self_attn.out_proj.bias',
//         'ar_decoder.layers.9.linear1.weight',
//         'ar_decoder.layers.9.linear1.bias',
//         'ar_decoder.layers.9.linear2.weight',
//         'ar_decoder.layers.9.linear2.bias',
//         'ar_decoder.layers.9.norm1.weight',
//         'ar_decoder.layers.9.norm1.bias',
//         'ar_decoder.layers.9.norm2.weight',
//         'ar_decoder.layers.9.norm2.bias',
//         'ar_decoder.layers.10.self_attn.in_proj_weight',
//         'ar_decoder.layers.10.self_attn.in_proj_bias',
//         'ar_decoder.layers.10.self_attn.out_proj.weight',
//         'ar_decoder.layers.10.self_attn.out_proj.bias',
//         'ar_decoder.layers.10.linear1.weight',
//         'ar_decoder.layers.10.linear1.bias',
//         'ar_decoder.layers.10.linear2.weight',
//         'ar_decoder.layers.10.linear2.bias',
//         'ar_decoder.layers.10.norm1.weight',
//         'ar_decoder.layers.10.norm1.bias',
//         'ar_decoder.layers.10.norm2.weight',
//         'ar_decoder.layers.10.norm2.bias',
//         'ar_decoder.layers.11.self_attn.in_proj_weight',
//         'ar_decoder.layers.11.self_attn.in_proj_bias',
//         'ar_decoder.layers.11.self_attn.out_proj.weight',
//         'ar_decoder.layers.11.self_attn.out_proj.bias',
//         'ar_decoder.layers.11.linear1.weight',
//         'ar_decoder.layers.11.linear1.bias',
//         'ar_decoder.layers.11.linear2.weight',
//         'ar_decoder.layers.11.linear2.bias',
//         'ar_decoder.layers.11.norm1.weight',
//         'ar_decoder.layers.11.norm1.bias',
//         'ar_decoder.layers.11.norm2.weight',
//         'ar_decoder.layers.11.norm2.bias',
//         'ar_decoder.norm.weight',
//         'ar_decoder.norm.bias',
//         'ar_predict_layer.weight',
//         'nar_audio_embeddings.0.word_embeddings.weight',
//         'nar_audio_embeddings.1.word_embeddings.weight',
//         'nar_audio_embeddings.2.word_embeddings.weight',
//         'nar_audio_embeddings.3.word_embeddings.weight',
//         'nar_audio_embeddings.4.word_embeddings.weight',
//         'nar_audio_embeddings.5.word_embeddings.weight',
//         'nar_audio_embeddings.6.word_embeddings.weight',
//         'nar_audio_embeddings.7.word_embeddings.weight',
//         'nar_text_position.alpha',
//         'nar_audio_position.alpha',
//         'nar_decoder.layers.0.self_attn.in_proj_weight',
//         'nar_decoder.layers.0.self_attn.in_proj_bias',
//         'nar_decoder.layers.0.self_attn.out_proj.weight',
//         'nar_decoder.layers.0.self_attn.out_proj.bias',
//         'nar_decoder.layers.0.linear1.weight',
//         'nar_decoder.layers.0.linear1.bias',
//         'nar_decoder.layers.0.linear2.weight',
//         'nar_decoder.layers.0.linear2.bias',
//         'nar_decoder.layers.0.norm1.project_layer.weight',
//         'nar_decoder.layers.0.norm1.project_layer.bias',
//         'nar_decoder.layers.0.norm1.norm.weight',
//         'nar_decoder.layers.0.norm1.norm.bias',
//         'nar_decoder.layers.0.norm2.project_layer.weight',
//         'nar_decoder.layers.0.norm2.project_layer.bias',
//         'nar_decoder.layers.0.norm2.norm.weight',
//         'nar_decoder.layers.0.norm2.norm.bias',
//         'nar_decoder.layers.1.self_attn.in_proj_weight',
//         'nar_decoder.layers.1.self_attn.in_proj_bias',
//         'nar_decoder.layers.1.self_attn.out_proj.weight',
//         'nar_decoder.layers.1.self_attn.out_proj.bias',
//         'nar_decoder.layers.1.linear1.weight',
//         'nar_decoder.layers.1.linear1.bias',
//         'nar_decoder.layers.1.linear2.weight',
//         'nar_decoder.layers.1.linear2.bias',
//         'nar_decoder.layers.1.norm1.project_layer.weight',
//         'nar_decoder.layers.1.norm1.project_layer.bias',
//         'nar_decoder.layers.1.norm1.norm.weight',
//         'nar_decoder.layers.1.norm1.norm.bias',
//         'nar_decoder.layers.1.norm2.project_layer.weight',
//         'nar_decoder.layers.1.norm2.project_layer.bias',
//         'nar_decoder.layers.1.norm2.norm.weight',
//         'nar_decoder.layers.1.norm2.norm.bias',
//         'nar_decoder.layers.2.self_attn.in_proj_weight',
//         'nar_decoder.layers.2.self_attn.in_proj_bias',
//         'nar_decoder.layers.2.self_attn.out_proj.weight',
//         'nar_decoder.layers.2.self_attn.out_proj.bias',
//         'nar_decoder.layers.2.linear1.weight',
//         'nar_decoder.layers.2.linear1.bias',
//         'nar_decoder.layers.2.linear2.weight',
//         'nar_decoder.layers.2.linear2.bias',
//         'nar_decoder.layers.2.norm1.project_layer.weight',
//         'nar_decoder.layers.2.norm1.project_layer.bias',
//         'nar_decoder.layers.2.norm1.norm.weight',
//         'nar_decoder.layers.2.norm1.norm.bias',
//         'nar_decoder.layers.2.norm2.project_layer.weight',
//         'nar_decoder.layers.2.norm2.project_layer.bias',
//         'nar_decoder.layers.2.norm2.norm.weight',
//         'nar_decoder.layers.2.norm2.norm.bias',
//         'nar_decoder.layers.3.self_attn.in_proj_weight',
//         'nar_decoder.layers.3.self_attn.in_proj_bias',
//         'nar_decoder.layers.3.self_attn.out_proj.weight',
//         'nar_decoder.layers.3.self_attn.out_proj.bias',
//         'nar_decoder.layers.3.linear1.weight',
//         'nar_decoder.layers.3.linear1.bias',
//         'nar_decoder.layers.3.linear2.weight',
//         'nar_decoder.layers.3.linear2.bias',
//         'nar_decoder.layers.3.norm1.project_layer.weight',
//         'nar_decoder.layers.3.norm1.project_layer.bias',
//         'nar_decoder.layers.3.norm1.norm.weight',
//         'nar_decoder.layers.3.norm1.norm.bias',
//         'nar_decoder.layers.3.norm2.project_layer.weight',
//         'nar_decoder.layers.3.norm2.project_layer.bias',
//         'nar_decoder.layers.3.norm2.norm.weight',
//         'nar_decoder.layers.3.norm2.norm.bias',
//         'nar_decoder.layers.4.self_attn.in_proj_weight',
//         'nar_decoder.layers.4.self_attn.in_proj_bias',
//         'nar_decoder.layers.4.self_attn.out_proj.weight',
//         'nar_decoder.layers.4.self_attn.out_proj.bias',
//         'nar_decoder.layers.4.linear1.weight',
//         'nar_decoder.layers.4.linear1.bias',
//         'nar_decoder.layers.4.linear2.weight',
//         'nar_decoder.layers.4.linear2.bias',
//         'nar_decoder.layers.4.norm1.project_layer.weight',
//         'nar_decoder.layers.4.norm1.project_layer.bias',
//         'nar_decoder.layers.4.norm1.norm.weight',
//         'nar_decoder.layers.4.norm1.norm.bias',
//         'nar_decoder.layers.4.norm2.project_layer.weight',
//         'nar_decoder.layers.4.norm2.project_layer.bias',
//         'nar_decoder.layers.4.norm2.norm.weight',
//         'nar_decoder.layers.4.norm2.norm.bias',
//         'nar_decoder.layers.5.self_attn.in_proj_weight',
//         'nar_decoder.layers.5.self_attn.in_proj_bias',
//         'nar_decoder.layers.5.self_attn.out_proj.weight',
//         'nar_decoder.layers.5.self_attn.out_proj.bias',
//         'nar_decoder.layers.5.linear1.weight',
//         'nar_decoder.layers.5.linear1.bias',
//         'nar_decoder.layers.5.linear2.weight',
//         'nar_decoder.layers.5.linear2.bias',
//         'nar_decoder.layers.5.norm1.project_layer.weight',
//         'nar_decoder.layers.5.norm1.project_layer.bias',
//          'nar_decoder.layers.5.norm1.norm.weight',
//           'nar_decoder.layers.5.norm1.norm.bias',
//            'nar_decoder.layers.5.norm2.project_layer.weight', 
//            'nar_decoder.layers.5.norm2.project_layer.bias', 
//            'nar_decoder.layers.5.norm2.norm.weight', 
//            'nar_decoder.layers.5.norm2.norm.bias', 
//            'nar_decoder.layers.6.self_attn.in_proj_weight',
//             'nar_decoder.layers.6.self_attn.in_proj_bias',
//              'nar_decoder.layers.6.self_attn.out_proj.weight', 
//              'nar_decoder.layers.6.self_attn.out_proj.bias',
//               'nar_decoder.layers.6.linear1.weight', 
//               'nar_decoder.layers.6.linear1.bias', 
//               'nar_decoder.layers.6.linear2.weight',
//                'nar_decoder.layers.6.linear2.bias', 
//                'nar_decoder.layers.6.norm1.project_layer.weight', 
//                'nar_decoder.layers.6.norm1.project_layer.bias',
//                 'nar_decoder.layers.6.norm1.norm.weight',
//                  'nar_decoder.layers.6.norm1.norm.bias',
//                   'nar_decoder.layers.6.norm2.project_layer.weight',
//                    'nar_decoder.layers.6.norm2.project_layer.bias',
//                     'nar_decoder.layers.6.norm2.norm.weight',
//                      'nar_decoder.layers.6.norm2.norm.bias',
//                       'nar_decoder.layers.7.self_attn.in_proj_weight', 
//                       'nar_decoder.layers.7.self_attn.in_proj_bias', 
//                       'nar_decoder.layers.7.self_attn.out_proj.weight',
//                        'nar_decoder.layers.7.self_attn.out_proj.bias',
//                         'nar_decoder.layers.7.linear1.weight', 
//                         'nar_decoder.layers.7.linear1.bias', 
//                         'nar_decoder.layers.7.linear2.weight', 
//                         'nar_decoder.layers.7.linear2.bias',
//                          'nar_decoder.layers.7.norm1.project_layer.weight', 
//                          'nar_decoder.layers.7.norm1.project_layer.bias',
//                           'nar_decoder.layers.7.norm1.norm.weight', 
//                           'nar_decoder.layers.7.norm1.norm.bias',
//                            'nar_decoder.layers.7.norm2.project_layer.weight',
//                             'nar_decoder.layers.7.norm2.project_layer.bias', 
//                             'nar_decoder.layers.7.norm2.norm.weight', 
//                             'nar_decoder.layers.7.norm2.norm.bias', 
//                             'nar_decoder.layers.8.self_attn.in_proj_weight', 
//                             'nar_decoder.layers.8.self_attn.in_proj_bias', 
//                             'nar_decoder.layers.8.self_attn.out_proj.weight',
//                              'nar_decoder.layers.8.self_attn.out_proj.bias', 
//                              'nar_decoder.layers.8.linear1.weight', 
//                              'nar_decoder.layers.8.linear1.bias', 
//                              'nar_decoder.layers.8.linear2.weight',
//                               'nar_decoder.layers.8.linear2.bias', 
//                               'nar_decoder.layers.8.norm1.project_layer.weight',
//                                'nar_decoder.layers.8.norm1.project_layer.bias', 
//                                'nar_decoder.layers.8.norm1.norm.weight',
//                                 'nar_decoder.layers.8.norm1.norm.bias', 
//                                 'nar_decoder.layers.8.norm2.project_layer.weight',
//                                  'nar_decoder.layers.8.norm2.project_layer.bias',
//                                   'nar_decoder.layers.8.norm2.norm.weight', 
//                                   'nar_decoder.layers.8.norm2.norm.bias', 
//                                   'nar_decoder.layers.9.self_attn.in_proj_weight', 
//                                   'nar_decoder.layers.9.self_attn.in_proj_bias', 
//                                   'nar_decoder.layers.9.self_attn.out_proj.weight',
//                                    'nar_decoder.layers.9.self_attn.out_proj.bias', 
//                                    'nar_decoder.layers.9.linear1.weight', 
//                                    'nar_decoder.layers.9.linear1.bias', 
//                                    'nar_decoder.layers.9.linear2.weight', 
//                                    'nar_decoder.layers.9.linear2.bias', 
//                                    'nar_decoder.layers.9.norm1.project_layer.weight', 
//                                    'nar_decoder.layers.9.norm1.project_layer.bias', 
//                                    'nar_decoder.layers.9.norm1.norm.weight', 
//                                    'nar_decoder.layers.9.norm1.norm.bias', 
//                                    'nar_decoder.layers.9.norm2.project_layer.weight',
//                                     'nar_decoder.layers.9.norm2.project_layer.bias',
//                                      'nar_decoder.layers.9.norm2.norm.weight', 
//                                      'nar_decoder.layers.9.norm2.norm.bias', 
//                                      'nar_decoder.layers.10.self_attn.in_proj_weight', 
//                                      'nar_decoder.layers.10.self_attn.in_proj_bias',
//                                       'nar_decoder.layers.10.self_attn.out_proj.weight', 
//                                       'nar_decoder.layers.10.self_attn.out_proj.bias', 
//                                       'nar_decoder.layers.10.linear1.weight', 
//                                       'nar_decoder.layers.10.linear1.bias', 
//                                       'nar_decoder.layers.10.linear2.weight', 
//                                       'nar_decoder.layers.10.linear2.bias', 
//                                       'nar_decoder.layers.10.norm1.project_layer.weight',
//                                        'nar_decoder.layers.10.norm1.project_layer.bias', 
//                                        'nar_decoder.layers.10.norm1.norm.weight', 
//                                        'nar_decoder.layers.10.norm1.norm.bias', 
//                                        'nar_decoder.layers.10.norm2.project_layer.weight', 
//                                        'nar_decoder.layers.10.norm2.project_layer.bias', 
//                                        'nar_decoder.layers.10.norm2.norm.weight', 
//                                        'nar_decoder.layers.10.norm2.norm.bias', 
//                                        'nar_decoder.layers.11.self_attn.in_proj_weight', 
//                                        'nar_decoder.layers.11.self_attn.in_proj_bias', 
//                                        'nar_decoder.layers.11.self_attn.out_proj.weight', 
//                                        'nar_decoder.layers.11.self_attn.out_proj.bias', 
//                                        'nar_decoder.layers.11.linear1.weight', 
//                                        'nar_decoder.layers.11.linear1.bias',
//                                         'nar_decoder.layers.11.linear2.weight', 
//                                         'nar_decoder.layers.11.linear2.bias', 
//                                         'nar_decoder.layers.11.norm1.project_layer.weight', 
//                                         'nar_decoder.layers.11.norm1.project_layer.bias', 
//                                         'nar_decoder.layers.11.norm1.norm.weight', 
//                                         'nar_decoder.layers.11.norm1.norm.bias',
//                                          'nar_decoder.layers.11.norm2.project_layer.weight', 
//                                          'nar_decoder.layers.11.norm2.project_layer.bias', 
//                                          'nar_decoder.layers.11.norm2.norm.weight',
//                                           'nar_decoder.layers.11.norm2.norm.bias', 
//                                           'nar_decoder.norm.project_layer.weight', 
//                                           'nar_decoder.norm.project_layer.bias', 
//                                           'nar_decoder.norm.norm.weight', 
//                                           'nar_decoder.norm.norm.bias', 
//                                           'nar_predict_layers.0.weight', 
//                                           'nar_predict_layers.1.weight', 
//                                           'nar_predict_layers.2.weight', 
//                                           'nar_predict_layers.3.weight', 
//                                           'nar_predict_layers.4.weight', 
//                                           'nar_predict_layers.5.weight', 
//                                           'nar_predict_layers.6.weight', 
//                                           'nar_stage_embeddings.0.word_embeddings.weight', 
//                                           'nar_stage_embeddings.1.word_embeddings.weight', 
//                                           'nar_stage_embeddings.2.word_embeddings.weight', 
//                                           'nar_stage_embeddings.3.word_embeddings.weight', 
//                                           'nar_stage_embeddings.4.word_embeddings.weight', 
//                                           'nar_stage_embeddings.5.word_embeddings.weight', 
//                                           'nar_stage_embeddings.6.word_embeddings.weight', 
//                                           'ar_language_embedding.word_embeddings.weight', 
//                                           'nar_language_embedding.word_embeddings.weight'])

VALLF::VALLF(
        int d_model,
        int nhead,
        int num_layers,
        bool norm_first,
        bool add_prenet,
        TransformerEncoder *decoder_cls,
        TransformerEncoderLayer *decoder_layer_cls,
        int prefix_mode,
        bool share_embedding,
        float nar_scale_factor,
        bool prepend_bos,
        int num_token,
        int num_quantizers
) {

    this-> nar_d_model = int(d_model * nar_scale_factor);
    this->ar_text_embedding = new TokenEmbedding(d_model, num_token);
    this-> nar_text_embedding = new TokenEmbedding(nar_d_model, num_token);
    this-> ar_audio_prepend_bos = prepend_bos;

    if (add_prenet) {
        /* code */
    } else {
        this->ar_text_prenet = nullptr;
        this->nar_audio_prenet = nullptr;
    }

    this->ar_text_position = new SinePositionalEmbedding(
            d_model,
            0.1
//            false,
//            true
    );

    this->ar_audio_position = new SinePositionalEmbedding(
            nar_d_model,
            0.1
//            false,
//            true
    );
    this-> ar_decoder = new TransformerEncoder();
    this->ar_predict_layer = new TransformerEncoderLayer();
    //        rng = random.Random(0)
    this->num_heads = nhead;
    this->prefix_mode = prefix_mode;
    this->num_quantizers = num_quantizers;

    if (num_quantizers > 1) {
        //TODO init
        this->nar_audio_embeddings = nullptr;

        this->nar_text_position = new SinePositionalEmbedding(
                nar_d_model,
                0.1
//                false,
//                false
        );
        //TODO init
        this-> nar_decoder = nullptr;
        //TODO init
        this->nar_predict_layers = nullptr;
        //TODO init
        this-> nar_stage_embeddings = nullptr;

        if (share_embedding) {
            /* code */
        }

    }
}


bool VALLF::load_model_from_file() {
    return false;
}

VALLE::VALLE(
        int d_model,
        int nhead,
        int num_layers,
        bool norm_first,
        bool add_prenet,
        int prefix_mode,
        bool share_embedding,
        float nar_scale_factor,
        bool prepend_bos,
        int num_token,
        int quantizers
) : VALLF(
        d_model,
        nhead,
        num_layers,
        norm_first,
        add_prenet,
        new TransformerEncoder(),
        new TransformerEncoderLayer(),
        prefix_mode, share_embedding, nar_scale_factor, prepend_bos, num_token,
        quantizers) {
    this->ar_language_embedding = new TokenEmbedding(d_model, language_ID.size());
    this->nar_language_embedding = new TokenEmbedding(d_model, language_ID.size());
}

ggml_tensor *VALLE::inference(
        ggml_tensor *x,
        ggml_tensor *x_lens,
        ggml_tensor *y,
        ggml_tensor *enroll_x_lens,
        int top_k,
        float temperature,
        const std::string &prompt_language,
        const std::string &text_language,
        int best_of,
        float length_penalty,
        bool return_worst
) {
    const auto text = x;
//    auto x_embedding = ar_language_embedding->forward(text);
    //	auto	prompt_language_id
    return nullptr;
}